// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package taskclient

import (
	"context"

	"task/task"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = task.Request
	Response = task.Response

	Task interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTask struct {
		cli zrpc.Client
	}
)

func NewTask(cli zrpc.Client) Task {
	return &defaultTask{
		cli: cli,
	}
}

func (m *defaultTask) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := task.NewTaskClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
