// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"context"

	"task/internal/logic"
	"task/internal/svc"
	"task/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServer) Ping(ctx context.Context, in *task.Request) (*task.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
