// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	publishTaskFieldNames          = builder.RawFieldNames(&PublishTask{})
	publishTaskRows                = strings.Join(publishTaskFieldNames, ",")
	publishTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(publishTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	publishTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(publishTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	publishTaskModel interface {
		Insert(ctx context.Context, data *PublishTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PublishTask, error)
		Update(ctx context.Context, data *PublishTask) error
		Delete(ctx context.Context, id int64) error
		FindPublishTaskAmount(ctx context.Context, status int,genre string) (int64, error)
		FindPublishTaskList(ctx context.Context, tashkId,maxNum,startLine int32,genre string) ([]*PublishTask, error)
	}

	defaultPublishTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PublishTask struct {
		Id           int64        `db:"id"`
		CreatedAt    sql.NullTime `db:"created_at"`
		UpdatedAt    sql.NullTime `db:"updated_at"`
		DeletedAt    sql.NullTime `db:"deleted_at"`
		Creator      string       `db:"creator"`
		Status       int64        `db:"status"`
		TweetAddress string       `db:"tweet_address"`
		Label        string       `db:"label"`
		AwardBudget  float64      `db:"award_budget"`
		MaxUser      int64        `db:"max_user"`
		AwardAmount  float64      `db:"award_amount"`
		EndTime      time.Time    `db:"end_time"`
		Accomplish   int64        `db:"accomplish"`
	}
)

func newPublishTaskModel(conn sqlx.SqlConn) *defaultPublishTaskModel {
	return &defaultPublishTaskModel{
		conn:  conn,
		table: "`publish_task`",
	}
}

func (m *defaultPublishTaskModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPublishTaskModel) FindOne(ctx context.Context, id int64) (*PublishTask, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", publishTaskRows, m.table)
	var resp PublishTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPublishTaskModel) Insert(ctx context.Context, data *PublishTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, publishTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Creator, data.Status, data.TweetAddress, data.Label, data.AwardBudget, data.MaxUser, data.AwardAmount, data.EndTime, data.Accomplish)
	return ret, err
}

func (m *defaultPublishTaskModel) Update(ctx context.Context, data *PublishTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, publishTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Creator, data.Status, data.TweetAddress, data.Label, data.AwardBudget, data.MaxUser, data.AwardAmount, data.EndTime, data.Accomplish, data.Id)
	return err
}

func (m *defaultPublishTaskModel) tableName() string {
	return m.table
}

// FinParticipantAmount 获取任务数量
func (m *defaultPublishTaskModel) FindPublishTaskAmount(ctx context.Context, status int,genre string) (int64, error) {
	query := fmt.Sprintf("SELECT COUNT(*) FROM %s WHERE `%s` = ?", m.table,genre)
	var resp int64
	err := m.conn.QueryRow(&resp, query, status)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, ErrNotFound
	default:
		return 0, err
	}
}

// FindTaskList 按条件查询策展任务
func (m *defaultPublishTaskModel) FindPublishTaskList(ctx context.Context, tashkId,maxNum,startLine int32,genre string) ([]*PublishTask, error) {
	query := fmt.Sprintf("select %s from %s where `%s` = ? limit %s offset %s", publishTaskRows, m.table, genre, maxNum, startLine)
	var resp []*PublishTask
	err := m.conn.QueryRow(&resp, query, tashkId)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}