// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskTemplateFieldNames          = builder.RawFieldNames(&TaskTemplate{})
	taskTemplateRows                = strings.Join(taskTemplateFieldNames, ",")
	taskTemplateRowsExpectAutoSet   = strings.Join(stringx.Remove(taskTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taskTemplateRowsWithPlaceHolder = strings.Join(stringx.Remove(taskTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	taskTemplateModel interface {
		Insert(ctx context.Context, data *TaskTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TaskTemplate, error)
		Update(ctx context.Context, data *TaskTemplate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTaskTemplateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaskTemplate struct {
		Id       int64          `db:"id"`
		TaskId   sql.NullInt64  `db:"task_id"`
		TaskName sql.NullString `db:"task_name"`
	}
)

func newTaskTemplateModel(conn sqlx.SqlConn) *defaultTaskTemplateModel {
	return &defaultTaskTemplateModel{
		conn:  conn,
		table: "`task_template`",
	}
}

func (m *defaultTaskTemplateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaskTemplateModel) FindOne(ctx context.Context, id int64) (*TaskTemplate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskTemplateRows, m.table)
	var resp TaskTemplate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskTemplateModel) Insert(ctx context.Context, data *TaskTemplate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, taskTemplateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.TaskName)
	return ret, err
}

func (m *defaultTaskTemplateModel) Update(ctx context.Context, data *TaskTemplate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskTemplateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.TaskName, data.Id)
	return err
}

func (m *defaultTaskTemplateModel) tableName() string {
	return m.table
}
