// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	treasureTaskFieldNames          = builder.RawFieldNames(&TreasureTask{})
	treasureTaskRows                = strings.Join(treasureTaskFieldNames, ",")
	treasureTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(treasureTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	treasureTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(treasureTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	treasureTaskModel interface {
		Insert(ctx context.Context, data *TreasureTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TreasureTask, error)
		Update(ctx context.Context, data *TreasureTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTreasureTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TreasureTask struct {
		Id               int64        `db:"id"`
		CreatedAt        sql.NullTime `db:"created_at"`
		UpdatedAt        sql.NullTime `db:"updated_at"`
		DeletedAt        sql.NullTime `db:"deleted_at"`
		Name             string       `db:"name"`
		DemandIntegral   int64        `db:"demand_integral"`
		TaskReward       int64        `db:"task_reward"`
		ExperienceReward int64        `db:"experience_reward"`
		RewardQuantity   int64        `db:"reward_quantity"`
		Employ           int64        `db:"employ"`
	}
)

func newTreasureTaskModel(conn sqlx.SqlConn) *defaultTreasureTaskModel {
	return &defaultTreasureTaskModel{
		conn:  conn,
		table: "`treasure_task`",
	}
}

func (m *defaultTreasureTaskModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTreasureTaskModel) FindOne(ctx context.Context, id int64) (*TreasureTask, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", treasureTaskRows, m.table)
	var resp TreasureTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTreasureTaskModel) Insert(ctx context.Context, data *TreasureTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, treasureTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Name, data.DemandIntegral, data.TaskReward, data.ExperienceReward, data.RewardQuantity, data.Employ)
	return ret, err
}

func (m *defaultTreasureTaskModel) Update(ctx context.Context, data *TreasureTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, treasureTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Name, data.DemandIntegral, data.TaskReward, data.ExperienceReward, data.RewardQuantity, data.Employ, data.Id)
	return err
}

func (m *defaultTreasureTaskModel) tableName() string {
	return m.table
}
